require: rubocop-rspec

AllCops:
  DisabledByDefault: true
  TargetRubyVersion: 2.6.1
  TargetRailsVersion: 5.2

  Exclude:
    - db/**
    - bin/*
    - Gemfile
    - Gemfile.lock
    - '*.gemspec'
    - Rakefile
    - vendor/**/*
    - node_modules/**/*

Documentation:
  Enabled: false

Lint:
  Enabled: true

Layout:
  Enabled: true

Style:
  Enabled: true

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys

Style/AsciiComments:
  Enabled: false

Style/GuardClause:
  Enabled: false

Style/ClassAndModuleChildren:
  Enabled: false

Style/ClassVars:
  Enabled: false

Style/BlockDelimiters:
  Enabled: false

Style/Lambda:
  EnforcedStyle: literal

Style/LambdaCall:
  Enabled: false

Style/AndOr:
  Enabled: false

Naming/HeredocDelimiterCase:
  Enabled: true

Naming/UncommunicativeMethodParamName:
  Enabled: false

Performance/ChainArrayAllocation:
  Enabled: true

Rails:
  Enabled: true

Rails/UnknownEnv:
  Environments:
    - test
    - development
    - production

RSpec/MultipleExpectations:
  Enabled: true

RSpec/ExampleLength:
  Enabled: false

RSpec/RepeatedDescription:
  Enabled: false

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/DescribeClass:
  Enabled: true

RSpec/ScatteredSetup:
  Enabled: true